---
title: "lscs_dd"
author: "Montana Kay Lara"
date: "2024-01-30"
output: html_document
---

A. Packages
```{r setup, results='hide', message=FALSE}
library(GenomicSEM)
library(here)
```

B. Setup directory
```{r setup_dir}
munged.dir <- here("munge_sumstats/munged_data_dd")
ld.dir <- here("ldsc/ld_scores_dd_wchr")
wld.dir <- here("ldsc/ld_scores_dd_wchr")
```

```{r filerename}
#rename files UGH
# ONLY DO THIS ONCE!
ldscore_files <- list.files(ld.dir, full.names = TRUE)
new_names <- substring(basename(ldscore_files), 13)
new_file_paths <- file.path(dirname(ldscore_files), new_names)
file.rename(ldscore_files, new_file_paths)
```

C. run 'ldsc()'
```{r ldsc}
# run multivariate ldsc

#traits point to munged data
traits <- list.files(munged.dir, full.names = TRUE)
trait_names <- c("a_indiff0", "b_indiff2", "c_indiff4", "d_indiff8", "e_indiff16", "f_indiff24")
sample.prev <- rep(NA, length(traits))
population.prev <- rep(NA, length(traits))

LDSCoutput <- ldsc(traits = traits, sample.prev = sample.prev, population.prev = population.prev, ld = ld.dir, wld = wld.dir, trait.names = trait_names, chr = 20)

save(LDSCoutput, file="LDSCoutput_dd.RData")
```